### ISSUE TITLE
Duplicate Zip Exception

### ISSUE THREAD

**Issue by zenyagami** [algolia/algoliasearch-client-android#88]
After add algoliat library the sync is OK, however i receive this message when i try to run (if i remove the library works fine)
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v7/appcompat/R$anim.class

i tried gradlew clean and, re build the project, clean, and this
 compile ('com.algolia:algoliasearch-android:3.2@aar')
        {
            exclude group: 'com.android.support', module: 'appcompat-v7'
        }
but is not working

**Comment by zenyagami** [comment]
seems this only happens with 3.2 version, 3.0 is ok.

**Comment by vinaybn92** [comment]
3.1 is also ok it seems.

**Comment by clement-leprovost** [comment]
Indeed, `classes.jar` in `algoliasearch-android-3.2.aar` contains the `android.support.v7.appcompat.R` class, which I can't explain. Another thing that I can't explain is why Android Studio deals with it just fine, whereas command-line Gradle rightfully complains. Unit tests don't complain either ([version 3.2 passed](https://travis-ci.org/algolia/algoliasearch-client-android/builds/133135394)), but since they use Robolectric and not a full-blown Android application, this makes more sense.

All right, I'm on it. Sorry for the inconvenience. :/

**Comment by clement-leprovost** [comment]
I have just asked Sonatype to remove version 3.2 from Maven Central. I will re-publish it later with a fixed archive.

Note: that will make the version unavailable for at least a few hours. But I didn't want to just publish a 3.2.1 and let a broken version linger in the repository.

**Comment by clement-leprovost** [comment]
OK, could not remove the 3.2 version from Maven. It is the standard policy, which makes sense, but since the version was not actually usable, I thought we could do an exception. Anyway:

Version 3.2.1 is out which fixes this issue. Happy coding!
